# backend/app/config.py

# MySQL 데이터베이스 설정
MYSQL_HOST = ""
MYSQL_ACCOUNT = ""
MYSQL_PASSWORD = ""
MYSQL_DATABASE = ""

SQLALCHEMY_DATABASE_URI = (
    f"mysql+pymysql://{MYSQL_ACCOUNT}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DATABASE}"
)
SQLALCHEMY_TRACK_MODIFICATIONS = False
